"""Shared exception taxonomy. Every unresolved record gets exactly one of
these codes plus a human-readable reason - never silently dropped."""

NO_CANDIDATE_FOUND = "NO_CANDIDATE_FOUND"
AMBIGUOUS_MULTIPLE_CANDIDATES = "AMBIGUOUS_MULTIPLE_CANDIDATES"
AMOUNT_MISMATCH_UNEXPLAINED = "AMOUNT_MISMATCH_UNEXPLAINED"
VERIFIER_REJECTED = "VERIFIER_REJECTED"

ALL_TYPES = [
    NO_CANDIDATE_FOUND,
    AMBIGUOUS_MULTIPLE_CANDIDATES,
    AMOUNT_MISMATCH_UNEXPLAINED,
    VERIFIER_REJECTED,
]
